export const Alltextinfo={
    loginfirstboldtext:"RAISING ABOVE",
    loginsecond:"Providing Exceptional Advice and Service to Our Clients.",
    loginwelcometext:"Welcome Back",
    registerwelcome:"Connect With As",
    username:"Username",
    password:"Password",
    email:"Email",
    reenterpassword:"Re-enter your password",
    usernametype:"text",
    passwordtype:"password",
    usernameplaceholder:"Enter your username",
    passwordplaceholder:"Enter your password",
    renterpasswordplaceholder:"Re-enter your password",
    emailplaceholder:"Enter your email address",
    signintext:"Sign In",
    signontext:"Sign Up",
    forgotusername:"Forgot Username?",
    forgotpassword:"Forgot Password?",
    newusertext:"New User?",
    registertext:"Register Here",
    usernameerror:"Please enter a valid username!",
    passworderror:"you have to enter at least 8 digit!",
}
export const Textcolorcode={
    normalfont:"18px",
    normalfontweight:"normal",
    boldfont:"26px",
    boldfontweight:"bold",
    firstimagewidth:"100%",
    fisrtimageheight:"100vh",
    secondimagewith:"26%",
    secodnimageheight:"63px",
    firstimagerepeat:"unset",
    secondimagerepeat:"no-repeat,no-repeat",
    textalignfirst:"center",
    textalignsecond:"left",
    textunderlinetrue:"underline",
    textcolortrue:"blue",
    textunderlinefalse:"none",
    textcolorfalse:"black",
    firstsidecolor:"white",
    secondsidecolr:"black",
    errorcolor:"red",
    normalbuttoncolor:"#34bbf0",
    normalbuttoncursor:"pointer",
    errorbuttoncorlr:"lightgray",
    errorbuttoncursor:"no-drop",
    backiconwidth:"30%",
    backiconheight:"30px",
    backimagemargin:"inherit",
    imagemargin:"auto",
    errorfont:"14px"
}